// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRUZeQ9Vtm1wff6CDNGPImANW9uu-Zy60',
    appId: '1:959177740121:web:c7ee7b43f3011900fe4648',
    messagingSenderId: '959177740121',
    projectId: 'stylesync-4b86c',
    authDomain: 'stylesync-4b86c.firebaseapp.com',
    storageBucket: 'stylesync-4b86c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeoGVpBDtnFKFd9LctgGG2Z0xxuzDoknQ',
    appId: '1:959177740121:android:40d6d3570c71d6e2fe4648',
    messagingSenderId: '959177740121',
    projectId: 'stylesync-4b86c',
    storageBucket: 'stylesync-4b86c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7zozFbkukmgy0E2aETvZA4QVjItwMoN4',
    appId: '1:959177740121:ios:9f8586bb05c6c732fe4648',
    messagingSenderId: '959177740121',
    projectId: 'stylesync-4b86c',
    storageBucket: 'stylesync-4b86c.firebasestorage.app',
    iosClientId: '959177740121-c5m4ajt908ub9f7onaq05i9ut6p8tfdd.apps.googleusercontent.com',
    iosBundleId: 'es.zaitec.styleSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7zozFbkukmgy0E2aETvZA4QVjItwMoN4',
    appId: '1:959177740121:ios:9f8586bb05c6c732fe4648',
    messagingSenderId: '959177740121',
    projectId: 'stylesync-4b86c',
    storageBucket: 'stylesync-4b86c.firebasestorage.app',
    iosClientId: '959177740121-c5m4ajt908ub9f7onaq05i9ut6p8tfdd.apps.googleusercontent.com',
    iosBundleId: 'es.zaitec.styleSync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRUZeQ9Vtm1wff6CDNGPImANW9uu-Zy60',
    appId: '1:959177740121:web:49a555db744481c4fe4648',
    messagingSenderId: '959177740121',
    projectId: 'stylesync-4b86c',
    authDomain: 'stylesync-4b86c.firebaseapp.com',
    storageBucket: 'stylesync-4b86c.firebasestorage.app',
  );
}
