// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-vAbCexliU940aUnGZ1rx101O3j7c8CI',
    appId: '1:266462205003:web:2c87700f1813b72eb9e9ce',
    messagingSenderId: '266462205003',
    projectId: 'zaitec-barber',
    authDomain: 'zaitec-barber.firebaseapp.com',
    storageBucket: 'zaitec-barber.firebasestorage.app',
    measurementId: 'G-W3SYV70ZMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS3JFjtYez6FKdRNXpOiuGqoeU83gVthI',
    appId: '1:266462205003:android:bd3219cd7d65065bb9e9ce',
    messagingSenderId: '266462205003',
    projectId: 'zaitec-barber',
    storageBucket: 'zaitec-barber.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlbc3rnznmMpL75DjShxkyetX2uwf5HxE',
    appId: '1:266462205003:ios:aedb5f9148e2fea2b9e9ce',
    messagingSenderId: '266462205003',
    projectId: 'zaitec-barber',
    storageBucket: 'zaitec-barber.firebasestorage.app',
    iosBundleId: 'es.zaitec.styleSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlbc3rnznmMpL75DjShxkyetX2uwf5HxE',
    appId: '1:266462205003:ios:aedb5f9148e2fea2b9e9ce',
    messagingSenderId: '266462205003',
    projectId: 'zaitec-barber',
    storageBucket: 'zaitec-barber.firebasestorage.app',
    iosBundleId: 'es.zaitec.styleSync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-vAbCexliU940aUnGZ1rx101O3j7c8CI',
    appId: '1:266462205003:web:74e238d4ce11378eb9e9ce',
    messagingSenderId: '266462205003',
    projectId: 'zaitec-barber',
    authDomain: 'zaitec-barber.firebaseapp.com',
    storageBucket: 'zaitec-barber.firebasestorage.app',
    measurementId: 'G-CHR8WYL9ZH',
  );

}